apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9100'
spec:
  type: ClusterIP
  selector:
    app: node-exporter
  ports:
    - name: ne-tcp
      protocol: TCP
      port: 9100
      targetPort: 9100