apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: vpn
  labels:
    name: postgres
spec:
  type: NodePort
  ports:
    - name: psql-tcp
      targetPort: 5432
      protocol: TCP
      port: 5432
      nodePort: 32432
  selector:
    name: postgres