apiVersion: v1
kind: Service
metadata:
  name: shadowsocks
  namespace: vpn
  labels:
    name: shadowsocks
spec:
  type: ClusterIP
  ports:
    - name: ss-tcp
      targetPort: 22497
      protocol: TCP
      port: 22497
  selector:
    name: shadowsocks