apiVersion: v1
kind: Service
metadata:
  name: vpn-bot
  namespace: vpn
  labels:
    name: vpn-bot
spec:
  type: ClusterIP
  ports:
    - name: vpn-bot-tcp
      targetPort: 80
      protocol: TCP
      port: 80
  selector:
    name: vpn-bot