apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      serviceAccountName: prometheus
      volumes:
        - name: prometheus-config
          secret:
            secretName: prometheus-config
      containers:
        - name: prometheus
          image: "prom/prometheus:latest"
          imagePullPolicy: Always
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
              readOnly: false
          ports:
            - name: prometheus-tcp
              containerPort: 9090
              protocol: TCP