---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: gitlab-pv-data
spec:
 capacity:
    storage: 50Gi
 accessModes:
    - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 local:
    path: /opt/course_storages/gitlab/data
 nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - smart.house.home

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-data
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  volumeName: gitlab-pv-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: gitlab-pv-logs
spec:
 capacity:
    storage: 10Gi
 accessModes:
    - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 local:
    path: /opt/course_storages/gitlab/logs
 nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - smart.house.home

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-logs
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: gitlab-pv-logs

---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: gitlab-pv-config
spec:
 capacity:
    storage: 8Gi
 accessModes:
    - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 local:
    path: /opt/course_storages/gitlab/config
 nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - smart.house.home

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-config
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  volumeName: gitlab-pv-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: gitlab
 namespace: gitlab
spec:
 replicas: 1
 selector:
    matchLabels:
      app: gitlab
 template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: |
              external_url 'http://gitlab.ublin.keenetic.pro'
              letsencrypt['enable'] = false
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-config
        - mountPath: /var/log/gitlab
          name: gitlab-logs
        - mountPath: /var/opt/gitlab
          name: gitlab-data
      volumes:
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-pvc-config
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-pvc-logs
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-pvc-data

---
apiVersion: v1
kind: Service
metadata:
 name: gitlab
 namespace: gitlab
spec:
 type: NodePort
 ports:
 - port: 80
   targetPort: 80
   protocol: TCP
   name: http
   nodePort: 31111
 - port: 22
   targetPort: 22
   protocol: TCP
   name: ssh
   nodePort: 30222
 selector:
    app: gitlab