apiVersion: v1
kind: Service
metadata:
  name: stubby
  namespace: vpn
  labels:
    name: stubby
spec:
  type: NodePort
  ports:
    - name: stubby-tcp
      targetPort: 53
      protocol: TCP
      port: 53
      nodePort: 30053
    - name: stubby-udp
      targetPort: 53
      protocol: UDP
      port: 53
      nodePort: 30053
  selector:
    name: stubby